config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :utentis, :path_prefix => 'my'#, :skip => [:registrations]
  resources :utentis

  root to: "welcome#index"
  get 'welcome/aperti', :path => "aperti"
  get 'welcome/prelogin'
  get 'welcome/justone'
  post 'welcome/justone'
  get 'welcome/login', :path => 'login'
  get 'welcome/login'
  get 'welcome/assegnati', :path => 'assegnati'
  get 'welcome/elenco', :path => 'elenco'
  get 'welcome/richiedi', :path => 'richiedi'
  post 'welcome/richiesta'
  post 'welcome/registrazione', :path => 'registrazione'

  

  resources :clienti do
    resources :contrattis
    resources :interventi do
      
      get :sms
      get :allega
      get :vediallegato
      patch :salva_allegato
      get :elimina_allegato
        resources :intallegatis
        resources :comunicazioni
        resources :works do
          get :allega
          patch :salva_allegato
          get :elimina_allegato
          get :vedi_allegato
        end
    end
  end

 
  

  

end

app/models/interventi.rb
class Interventi < ActiveRecord::Base
  belongs_to :clienti, :foreign_key => "cliente_id"
  has_many :comunicazionis, :dependent => :destroy
  has_many :works, :dependent => :destroy
  #allegati intervento
  has_many :intallegatis, :dependent => :destroy
  #has_attached_file :rapportino#, { url: "/system/:hash.:extension", hash_secret: "longSecretString" }
  
  #do_not_validate_attachment_file_type :rapportino
  #validates_attachment_content_type :rapportino, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]

  #validates_attachment_content_type :rapportino, content_type: /.pdf\Z/
  #validates_attachment_file_name :rapportino, :matches => [/png\Z/, /jpe?g\Z/, /pdf\Z/, /gif\Z/, /jpg\Z/]
  #validates_attachment_content_type :rapportino, content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf"]
  #validates_attachment :rapportino, :content_type => {:content_type => %w(image/jpeg image/jpg image/png application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document)}

  #do_not_validate_attachment_file_type :rapportino

  #has_one :utenti, :foreign_key => "operator_id"

  validates :data, presence: true
  validates :intervento, presence: true, length: {minimum: 5 }
  #validates :durata, presence: true

end

app/controllers/interventi_controller.rb
class InterventiController < ApplicationController

	#before_action :authenticate_utenti!
	before_filter :authenticate_utenti!
	before_filter :is_admin?, :except => :show
	before_filter :is_operatore?, :only => :show

	#per ispezionare i valori passati in POST
	#render plain: params[:intervento].inspect
	
	def index
		
		@clienti = Clienti.find(params[:clienti_id])
		@titolo = "Elenco Interventi - #{@clienti.nome}"
		#@interventi = Interventi.select("interventis.id, interventis.data, interventis.intervento, COUNT(comunicazionis.id) AS tot_comunicazioni, interventis.chiuso").joins('LEFT OUTER JOIN comunicazionis ON interventis.id = comunicazionis.interventi_id').where(cliente_id: params[:clienti_id]).group("interventis.id").order("interventis.data DESC")
		@interventi = Interventi.where(:cliente_id => @clienti)
	end


	def show
		@titolo = "Dettaglio Intervento"
		@clienti = Clienti.find(params[:clienti_id])
		@interventi = Interventi.where(cliente_id: @clienti).find(params[:id])
		@tecnico = Utenti.find(@interventi.operator_id) if @interventi.operator_id
		@allegati = Intallegati.where(:interventi_id => @interventi)

		@tecnici = Utenti.where(operatore: '1')

		rescue ActiveRecord::RecordNotFound  
		 flash[:errore] = "Errore nella query - interventi"
		 redirect_to :controller => "welcome", :action => "index"
		return

	end


	def new
		@titolo = "Nuovo Intervento"
		@interventi = Interventi.new
		@clienti = Clienti.find(params[:clienti_id])	
		#@clienti = Clienti.find(params[:id])
	end


	def edit
		@titolo = "Modifica Intervento"
		@clienti = Clienti.find(params[:clienti_id])
		@interventi = Interventi.where(cliente_id: @clienti).find(params[:id])
		rescue ActiveRecord::RecordNotFound  
		 flash[:errore] = "Errore nella query - interventi"
		 redirect_to :controller => "welcome", :action => "index"
		return
	end


	def create
		@titolo = "Nuovo Intervento"
		@clienti = Clienti.find(params[:clienti_id])
		@interventi = Interventi.new(parametri_intervento)
		@interventi.codice = SecureRandom.hex(2)
		if @interventi.save
			redirect_to clienti_interventi_path(:id => @interventi)
		else
			render 'new'
		end
	end


	def update
		@clienti = Clienti.find(params[:clienti_id])
		@interventi = Interventi.where(cliente_id: @clienti).find(params[:id])
		if @interventi.update(parametri_intervento)
			redirect_to clienti_interventi_path(:id => @interventi)
		else
			render 'edit'
		end
	end


	def destroy
		@clienti = Clienti.find(params[:clienti_id])
		@interventi = Interventi.where(cliente_id: @clienti).find(params[:id])
		@interventi.destroy
		redirect_to clienti_interventi_index_path(params[:clienti_id])
	end

	def sms
		@clienti = Clienti.find(params[:clienti_id])
		@interventi = Interventi.where(cliente_id: @clienti).find(params[:interventi_id])
		@sms = Skuby::Gateway.send_sms('Messaggio di prova', '393291529641')
		if @sms.success? #=> true
			redirect_to clienti_interventi_index_path
			#redirect_to clienti_interventi_index_path(:esitosms => @sms.success)
		end
	end

# ----------------------------GESTIONE ALLEGATI
	def allega
		@titolo = "Allega Rapportino"
		@clienti = Clienti.find(params[:clienti_id])
		#@interventi = Interventi.where(cliente_id: @clienti).find(params[:id])
		@interventi = Interventi.find(params[:interventi_id])
		#rescue ActiveRecord::RecordNotFound  
		# flash[:errore] = "Errore nella query - interventi"
		# redirect_to :controller => "welcome", :action => "index"
		#return
	end

	def salva_allegato
		@clienti = Clienti.find(params[:clienti_id])
		#@interventi = Interventi.where(cliente_id: @clienti).find(params[:id])
		@interventi = Interventi.find(params[:interventi_id])
		if @interventi.update(parametri_allegato)
		#if @interventi.update(params[:rapportino])
		#if @interventi.update
			redirect_to clienti_interventi_path(:id => @interventi)
		else
			render 'allega'
		end
	end

	def vediallegato
		@id_allegato = params[:allegato]
		@allegato = Intallegati.find(@id_allegato)
		
		if @allegato.autore
			@autore = Utenti.find(@allegato.autore).nome
		else
			@autore = 'N/A'
		end
		#find(params[:clienti_id])
	end

	def elimina_allegato
	@clienti = Clienti.find(params[:clienti_id])
	@interventi = Interventi.find(params[:interventi_id])
	@interventi.rapportino = nil
	@interventi.save
	redirect_to clienti_interventi_path(:id => @interventi)


	end


	
	private
		def parametri_intervento
			#params.require(:interventi).permit(:cliente_id, :data, :apparecchiatura, :intervento, :durata, :note, :chiuso, :codice, :operator_id)
			params.require(:interventi).permit(:cliente_id, :data, :apparecchiatura, :intervento, :note, :chiuso, :codice, :operator_id, :monteore)
		end

		def parametri_tecnico
			params.require(interventi).permit(operator_id)
		end

		def parametri_allegato
			params.require(:interventi).permit(:rapportino)
		end

		

end

app/helpers/interventi_helper.rb
module InterventiHelper
end

app/views/interventi/_allegatoshowmodal.html.erb
<div class="modal-header">
<h3>Dettagli allegato</h3>
<p><%#= cazz %></p>
</div>

app/views/interventi/_form.html.erb
    <div class="row">
      <div class="col-md-12">
        <h4>Cliente: <%= @clienti.nome %> - [<%= @clienti.id %>]</h4>
      </div>
    </div>


    <% if local_assigns.has_key? :url %>
      <%= form_for :interventi, url: url, method: method do |f| %>

    



    <div class="row">
      <div class="col-md-2">
        <div class="form-group">
          <%= f.label :data, 'Data creazione' %>
          <%= f.text_field :data, :class => "date-picker form-control input-mini", :value => Time.now.strftime("%Y/%m/%d"), readonly: true %>
          <span class="help-block">formato YYY-MM-DD</span>
        </div>
      </div>
    </div>


    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label "Problema dichiarato o riscontrato" %>
          <%= f.text_area :intervento, maxlength: 200, class: 'form-control limited' %>
        </div>
      </div>
    </div>


     <!-- -->
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <%= f.label :note %>
          <%= f.text_area :note, maxlength: 200, class: 'form-control limited' %>
        </div>
      </div>
    </div>
     <!-- --> 

<%#= f.hidden_field :cliente_nome, :value => @clienti.nome, readonly: true, class: 'form-control' %>
<%= f.hidden_field :cliente_id, :value => @clienti.id %>


<div class="divider"></div>
  
    <!-- Switch per apertura - chiudsura intervento -->

    <div class="row">
      <div class="col-md-4">
        <label class="checkbox-inline">
         <%= f.check_box :chiuso, class: 'flat-green' %>
          Intervento Chiuso ?
        </label>
      </div>
      <div class=" row">
        <div class="col-md-4">
          <label class="checkbox-inline">
            <%= f.check_box :monteore, class: 'flat-green' %>
            Ore a scalare dal monteore?
        </label>
        </div>
      </div>    

    </div>

    <div class="divider"></div>
    
    <div class="row">
      <div class="col-md-3">
        <div class="form-group">
          <%= link_to 'Indietro', clienti_path(:id => @clienti.id), class: 'btn btn-danger' %>
          <%= f.submit 'Salva', :class => 'btn btn-success' %>
        </div>
    </div>




  </div>

<% end %>







<% end %>



app/views/interventi/allega.html.erb
<%= render'gestione_errori' %>

<%= form_for :interventi, url: clienti_interventi_salva_allegato_path , :method => 'patch', html: { multipart: true } do |f| %>

<div class="row">
	<div class="col-lg-4">

		<div class="form-group">
	    <%= f.label :rapportino %>
	    <%= f.file_field :rapportino, class: 'form-control' %>
	  </div>


	</div>
</div>

<%= link_to 'Indietro', clienti_interventi_path(:id => @interventi), class: 'btn btn-danger' %>
<%= f.submit 'Upload', class: 'btn btn-primary' %>

<% end %>

<%= debug(params) %>

app/views/interventi/edit.html.erb


<%= render'gestione_errori' %>

<%= render 'form', {url: clienti_interventi_path(@clienti, @interventi), method: 'patch'} %>

<div class="divider"></div>



<%= debug(params) %>

app/views/interventi/index.html.erb


<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="clip-cube-2"></i>
				Elenco Interventi
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
			<!-- <div class="dataTable_wrapper"> -->
				<table class="table table-hover" id="dataTables-interventi">
					<thead>
						<tr>
							<th>Descrizione</th>
							<th>Data</th>
							<!--<th>Apri</th>-->
							<th>Stato</th>
							<th>Operatore</th>
							<!--<th>Allegato</th>-->
							<th>MSG</th>
							<th>MSG-Count</th>
						</tr>
					</thead>

					<tbody>
						<% @interventi.each do |intervento| %>
						<% @sms = Comunicazioni.where(interventi_id: intervento.id ).count(:id) if Comunicazioni.where(interventi_id: intervento.id ) %>
						<tr>
							<td><%= link_to intervento.intervento, clienti_interventi_path(:id => intervento.id) %></td>
							<td><%= intervento.data.strftime("%d/%m/%Y") %></td>
							<!--<td><%= link_to '<i class="fa fa-folder-open"></i>'.html_safe, clienti_interventi_path(:id => intervento.id), :class => 'btn btn-blue' %></td>-->
							<td class="center"><% if intervento.chiuso == false %>
								<%#= image_tag("warning_32.png", size: '25x25', alt: 'Intervento Aperto') %>
								<span class="label label-danger"> <i class="fa fa-exclamation-circle"></i></span>
								<% end %>
							</td>
							<td><%= Utenti.find(intervento.operator_id ).nome if intervento.operator_id?		%></td>
							<!--<td class="center">
								<%# if intervento.rapportino.exists? %>
									<%#= link_to '<i class="clip-attachment"></i>'.html_safe, intervento.rapportino.url, target: '_blank', :class => 'btn btn-green' %>
								<%# end %>
							</td>-->
							<td>
								<%= link_to '<i class="material-icons" title="Invia Comunicazione">textsms</i>'.html_safe, new_clienti_interventi_comunicazioni_path(:interventi_id => intervento.id) %>
							</td>
							<td>
								<div class="chip">
									<%= image_tag("sms_128.png", size: '25x25') %>
									<%= @sms if @sms > 0 %>
							  	</div>
							</td>	
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>



<div class="row">
	<div class="col-lg-12">
		<%= link_to 'Indietro', clienti_path(@clienti.id), class: 'btn btn-danger' %>
		<%= link_to 'Nuovo Intervento', new_clienti_interventi_path(@clienti), class: 'btn btn-success' %>
	</div>
</div>

<div class="divider"></div>

<%= debug(params) %>

<script>
	$(document).ready(function() {
		$( '#dataTables-interventi' ).dataTable({
				responsive: true,
				//sort: "Proprietario"
				//"order": [[ 0, "desc" ]],
				 "oLanguage": {
								"sLengthMenu": "Visualizza _MENU_ records per pagina",
								"sZeroRecords": "Nessun risultato - spiacente",
								"sInfo": "Stai visualizzando i record da _START_ a _END_ (_TOTAL_ in totale)",
								"sInfoEmpty": "Nessun record disponibile",
								"sInfoFiltered": "(filtrati fra _MAX_ record totali)",
								"oPaginate": {
											  "sNext": "Successiva",
											  "sPrevious": "Precedente"
											}
							}
		});
	});
</script>

app/views/interventi/new.html.erb


<%= render'gestione_errori' %>


<%#= render 'form' %>
<%= render 'form', {url: clienti_interventi_index_path, method: 'nessuno'} %>


<div class="divider"></div>



<%= debug(params) %>


app/views/interventi/show.html.erb
<div class="row space12">
	<ul class="mini-stats col-sm-12">
		<li class="col-sm-4 col-xs-4">
			<div class="values">
				<i class="clip-user-4 circle-icon circle-green"></i>
				<strong><span data-original-title="Nome Cliente" data-placement="bottom" data-trigger="hover" class="popovers"><%= @clienti.nome %></strong>
			</div>
		</li>
		<li class="col-sm-4 col-xs-4">
			<div class="values">
				<i class="clip-settings circle-icon circle-bricky"></i>
				<strong><span data-original-title="Codice Cliente" data-content="Necessario per JustOne" data-placement="bottom" data-trigger="hover" class="popovers"><%= @interventi.cliente_id %></span></strong>
				
			</div>
		</li>
		<li class="col-sm-4 col-xs-4">
			<div class="values">
				<i class="clip-target circle-icon circle-teal"></i>
				<strong><span data-original-title="Codice Intervento" data-content="Necessario per JustOne" data-placement="bottom" data-trigger="hover" class="popovers"><%= @interventi.codice %></span></strong>
				
			</div>
		</li>
		<!--
		<li class="col-sm-3 col-xs-3">
			<div class="values">
				<i class="clip-clip circle-icon circle-fuxia"></i>
				<strong>
					<%# if !@interventi.rapportino.exists? %>
						<%= link_to 'Rapportino Mancante', clienti_interventi_allega_path(:interventi_id => @interventi), class: 'btn btn-bricky' %>
					<%# else %>
						<%#= link_to 'Scheda Intervento', @interventi.rapportino.url %>
						<strong>Allegato Presente</strong>
						<%= link_to 'Apri <i class="fa fa-external-link"></i>'.html_safe, '#responsive2', "data-toggle" => "modal"	%>
					<%# end %>
				</strong>
			</div>
		</li>
		-->
	</ul>
</div>
<div class="divider"></div>
<!-- 		-->
<div class="row">
	<div class="col-lg-4">
		<div class="well well-sm">
			<div class="row center">
				<div class="col-lg-10">
					<h3>Descrizione Intevento</h3>
				</div>
				<div class="col-lg-2">
					<div class="dropdown pull-right">
					  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Azioni <span class="caret"></span></button>
					  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					    <li><%= link_to 'Modifica', edit_clienti_interventi_path(:id => @interventi.id) %></li>
					    <li><%= link_to 'Elimina', clienti_interventi_path(:id => @interventi.id), method: :delete, data: { confirm: "Sicuro di voler eliminare l'intervento? Non sarà possibile recuperarlo" } %></li>
					    <li><%= link_to 'Invia Comunicazione', new_clienti_interventi_comunicazioni_path(:interventi_id => @interventi.id) %></li>
					  </ul>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<dl class="dl-horizontal">	
						<dt><strong>Data Intervento: </strong></dt>
						<dd><%= @interventi.data.strftime("%d/%m/%Y") %></dd>
						<dt><strong>Durata: </strong></dt>
						<dd><%= @interventi.works.sum(:durata) %> ore</dd>
						<dt><strong>Descrizione: </strong></dt>
						<dd><%= @interventi.intervento %></dd>
						<dt><strong>Note: </strong></dt>
						<dd><%= @interventi.note %></dd>
					</dl>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4 col-xs-12">
		<div class="well well-sm">
			<div class="row">
				<div class="col-lg-3 col-xs-6">
					<%= image_tag("operator-256.png", size: '128x128') %>
				</div>
				<div class="col-lg-9 col-xs-6">
						<div class="row center">
							<div class="col-xs-12">
								<h3>Tecnico Assegnato</h3><%= link_to '<i class="fa fa-external-link"></i>'.html_safe, '#responsive', "data-toggle" => "modal"	%>
							</div>
						</div>
						<div class="row">
							<div>
								<div class="col-lg-6 col-xs-12 center">
								<% if !@tecnico %>
									<%= link_to 'Assegna', '#responsive', "data-toggle" => "modal", class: 'btn btn-bricky btn-lg' %>
								<% else %>
								<h4><%= @tecnico.nome %></h4>
								<% end %>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-4 col-xs-12">
		<div class="well well-sm">
			<div class="row center">
				<div class="col-md-12"><h3>Allegati</h3></div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<table class="table table-hover" id="dataTables-allegati">
						<thead>
							<tr>
								<th>Nome File</th>
								<th>Tipologia</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
							<% @allegati.each do |a| %>
								<tr>
									<td><%= a.titolo %></td>
									<td><%= a.allegatoint_content_type %></td>
									<td><%= link_to 'apri', clienti_interventi_vediallegato_path(:interventi_id => @interventi, :allegato => a.id), remote: true %></td>
								</tr>
							<% end %>
						</tbody>
					</table>
					<%= link_to '<i class="fa fa-plus"></i> Aggiungi'.html_safe, new_clienti_interventi_intallegati_path(:interventi_id => @interventi), class: 'btn btn-green btn-block' %>
				</div>
			</div>
		</div>
	</div>

</div>
<div class="row"><!-- riga works -->
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="clip-cube-2"></i>
				Lavori eseguiti per l'intervento
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
			<!-- <div class="dataTable_wrapper"> -->
				<table class="table table-hover" id="dataTables-works">
					<thead>
						<tr>
							<th>Data</th>
							<th>Operatore</th>
							<th>Durata</th>
							<th>Descrizione</th>
							<th>Note</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @interventi.works.order("data asc").each do |w| %>
						<tr>
							<td><%= link_to w.data.strftime("%d/%m/%Y"), clienti_interventi_work_path(:interventi_id => @interventi, :id => w.id) %></td>
							<td>
								<%=w.operator_id ? Utenti.find(w.operator_id).nome : 'N/A' %>
							</td>
							<td><%= w.durata %> ore</td>
							<td><%= w.descrizione %></td>
							<td><%= w.note %></td>
							<td>
								<%#= link_to '<i class="fa fa-edit"></i>'.html_safe, edit_clienti_interventi_work_path(:interventi_id => @interventi, :id => w.id), class: 'btn btn-primary' %>
								<% if w.schedawork.exists? %>
									<%= link_to '<i class="clip clip-attachment"></i>'.html_safe, w.schedawork.url, target: '_blank', class: 'btn btn-purple' %>
								<% end %>
								<%#= link_to '<i class="fa fa-edit"></i>'.html_safe, clienti_interventi_work_path(:interventi_id => @interventi, :id => w.id), class: 'btn btn-primary' %>
							</td>	
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div><!-- fine riga works -->
<div class="divider"></div>
<br>
<div class="row">
	<div class="col-lg-12">
		<%= link_to 'Indietro', clienti_interventi_index_path(@clienti.id), class: 'btn btn-danger' %>
		<%= link_to "NuovoWork", new_clienti_interventi_work_path(:interventi_id => @interventi.id), class: 'btn btn-green' %>
	</div>
</div>
<br>
<%= debug(params) %>

app/views/interventi/vediallegato.js.erb
$("#allegato-modal").html("<%= escape_javascript(render template: 'intallegatis/show', :locals => { :var_allegato => @variab_allegato } ) %>")
$("#allegato-modal").modal("show")