config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :utentis, :path_prefix => 'my'#, :skip => [:registrations]
  resources :utentis

  root to: "welcome#index"
  get 'welcome/aperti', :path => "aperti"
  get 'welcome/prelogin'
  get 'welcome/justone'
  post 'welcome/justone'
  get 'welcome/login', :path => 'login'
  get 'welcome/login'
  get 'welcome/assegnati', :path => 'assegnati'
  get 'welcome/elenco', :path => 'elenco'
  get 'welcome/richiedi', :path => 'richiedi'
  post 'welcome/richiesta'
  post 'welcome/registrazione', :path => 'registrazione'

  

  resources :clienti do
    resources :contrattis
    resources :interventi do
      
      get :sms
      get :allega
      get :vediallegato
      patch :salva_allegato
      get :elimina_allegato
        resources :intallegatis
        resources :comunicazioni
        resources :works do
          get :allega
          patch :salva_allegato
          get :elimina_allegato
          get :vedi_allegato
        end
    end
  end

 
  

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  

  before_filter :is_operatore?, :only => :assegnati
  before_filter :is_admin?, :only => :aperti
  before_filter :authenticate_utenti!, :only => :elenco
  before_filter :is_user?, :only => :elenco


  def index
    if @sono_guest
      redirect_to :controller => "welcome", :action => "prelogin"
      return
    end
  	@conta_aperti = Interventi.where(chiuso: false).count
  	@credito_skebby = Skuby::Credit.balance

  end


  def aperti
  	@titolo =" Interventi in corso"
  	#@aperti = Interventi.select("interventis.data, interventis.intervento, clientis.nome, interventis.cliente_id, interventis.id").joins('INNER JOIN clientis ON interventis.cliente_id = clientis.id').where(chiuso: false).order("data ASC")
    @interventi = Interventi.where(chiuso: false)    
  end


	def assegnati
    @titolo = "Ciao #{current_utenti.nome},  questi sono i tuoi interventi."
		@assegnati = Interventi.where(operator_id: current_utenti.id) 
	end

  def elenco
    @titolo ="I miei Interventi"
    @interventi = Interventi.where(cliente_id: current_utenti.clienti_id)
  end  


  def prelogin
    if !@sono_guest
      redirect_to root_path
      return
    end    

  end

  def justone
    if !@sono_guest
      redirect_to root_path
      return
    end
    
    @cod_cliente = params[:justone][:cod_cli]
    @cod_intervento = params[:justone][:cod_int]

    if @cod_cliente.blank? || @cod_intervento.blank?
      flash[:danger] = 'Controlla i parametri inseriti. La ricerca non ha prodotto risultati'
      redirect_to :controller => "welcome", :action => "prelogin"
      return
    end

    @intervento = Interventi.where(:cliente_id => @cod_cliente, :codice => @cod_intervento ).first
    
    if !@intervento
      flash[:danger] = 'Intervento non trovato. Controlla i parametri'
      redirect_to :controller => "welcome", :action => "prelogin"
      return
    end

    @cliente = Clienti.find(@cod_cliente)

    ########### Gestione stati di lavorazione

    @stato_data_inserimento = @intervento.created_at
    @stato_tecnico_presente = 'assegnato' if @intervento.operator_id
    @stato_tecnico = Utenti.find(@intervento.operator_id) if @intervento.operator_id 
    @stato_numero_works =  @intervento.works.count

    @tecnico = Utenti.find(@intervento.operator_id) if @intervento.operator_id 

  end

  def richiedi
    if !@sono_user
      redirect_to root_path
      return
    end

    @titolo = "Richiedi Intervento"
    @interventi = Interventi.new
    @clienti = current_utenti.clienti_id

    # ------------------------------------------------
    # Calcolo ore residue per contratti acquistati
    @contrattis = Contratti.where(clienti_id: @clienti)
    @acquistate = Contratti.where(clienti_id: @clienti).sum(:ore)
    totaleore = Array.new
    Interventi.where(cliente_id: @clienti, :monteore => '1').each do |int|
      totaleore.push(Work.where(:interventi_id => int.id).sum(:durata))
    end
    @ore_usate = totaleore.sum
    @ore_rimanenti = @acquistate-@ore_usate
    # ------------------------------------------------

  end


  #metodo per salvataggio richiesta di intervento
  def richiesta
    @clienti = current_utenti.clienti_id
    @interventi = Interventi.new(parametri_intervento)
    @interventi.codice = SecureRandom.hex(2)
    @nomecliente = current_utenti.nome
    if @interventi.save
      #invio email
      UserTicket.richiesta(@nomecliente).deliver
      flash[:notice] = 'Nuova richiesta di  intervento inserita !!'
      redirect_to welcome_elenco_path
    else
      render 'richiedi'
    end
  end

  def registrazione




  end

  


  ###############################
  private

  def parametri_intervento
    params.require(:interventi).permit(:cliente_id, :data, :apparecchiatura, :intervento, :note, :chiuso, :codice, :operator_id, :monteore)
  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_body_registrazione.html.erb
<div class="main-container">

<% if !flash[:notice].blank? %>
	<section>
  	<div class = "alert alert-info"><%= flash[:notice] %></div>
 	</section>
<% end %>

<% if !flash[:error].blank? %>
	<section>
  	<div class = "alert alert-info"><%= alert %></div>
	</section>
<% end %>



<% flash.each do |key, value| %>
	<hr>
	<section>
		<div class="container">
			<div class="alert alert-<%= key %>">
				<button data-dismiss="alert" class="close">
					&times;
				</button>
				<i class="fa fa-exclamation-triangle"></i>
      	<strong>Attenzione!</strong> <%= value %>
      </div>
    </div>
  </section>
	<hr>
<% end %>


<br>

<section>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2>Compila la form sottostante per richiedere accesso al sistema</h2>
			</div>
		</div>

		<br>

		<%= form_for :registrazione, url: welcome_registrazione_path, method: 'nessuno' do |f| %>
		
			<div class="row">
				<div class="col-md-8">
					<div class="row">
						<div class="form-group">
							<div class="col-md-12">
								<%= f.label 'Nome / Rag. Sociale' %> <span class="symbol required"></span>
								<%= f.text_field :nome, :length=>"254", class: "form-control" %>
							</div>

							
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<%= f.label 'P.Iva / Rag. Sociale' %> <span class="symbol required"></span>
							<%= f.text_field :piva, :length=>"254", class: "form-control" %>
						</div>
						<div class="col-md-6">
							<%= f.label 'Cod.Fiscale / Rag. Sociale' %> <span class="symbol required"></span>
							<%= f.text_field :codfisc, :length=>"254", class: "form-control" %>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<%= f.label 'Indirizzo' %> <span class="symbol required"></span>
							<%= f.text_field :indirizzo, :length=>"254", class: "form-control" %>
						</div>
					</div>

					<div class="row">
						<div class="col-md-8">
							<%= f.label 'Città'.html_safe %> <span class="symbol required"></span>
							<%= f.text_field :citta, :length=>"254", class: "form-control" %>
						</div>
						<div class="col-md-2">
							<%= f.label 'C.A.P.' %> <span class="symbol required"></span>
							<%= f.text_field :cap, :length=>"254", class: "form-control" %>
						</div>
						<div class="col-md-2">
							<%= f.label 'Provincia' %> <span class="symbol required"></span>
							<%= f.text_field :provincia, :length=>"254", class: "form-control" %>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<%= f.label 'Telefono Fisso' %> <span class="symbol required"></span>
							<%= f.text_field :telefonofisso, :length=>"254", class: "form-control" %>
						</div>
						<div class="col-md-6">
							<%= f.label 'Cellulare' %> <span class="symbol required"></span>
							<%= f.text_field :telefono, :length=>"254", class: "form-control" %>
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<%= f.label 'Indirizzo Email (Login Utente)' %> <span class="symbol required"></span>
							<%= f.text_field :email, :length=>"254", class: "form-control" %>
						</div>
					</div>

					<div class="row">
						<div class="col-md-6">
							<%= f.label 'Indirizzo Email (Login Utente)' %> <span class="symbol required"></span>
							<%= f.text_field :password, :length=>"254", class: "form-control" %>
						</div>
						<div class="col-md-6">
							<%= f.label 'Indirizzo Email (Login Utente)' %> <span class="symbol required"></span>
							<%= f.text_field :confermapassword, :length=>"254", class: "form-control" %>
						</div>
					</div>

					<br>

					<div class="row">
						<div class="col-md-12">
							<h4 class="center">Condizioni di utilizzo</h4>

							<!-- Condizioni di utilizzo INIZIO -->
							<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus.</p>

							<p>Phasellus viverra nulla ut metus varius laoreet. Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus. Maecenas tempus, tellus eget condimentum rhoncus, sem quam semper libero, sit amet adipiscing sem neque sed ipsum. Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus. Nullam quis ante. Etiam sit amet orci eget eros faucibus tincidunt. Duis leo. Sed fringilla mauris sit amet nibh. Donec sodales sagittis magna. Sed consequat, leo eget bibendum sodales, augue velit cursus nunc, quis gravida magna mi a libero. Fusce vulputate eleifend sapien. Vestibulum purus quam, scelerisque ut, mollis sed, nonummy id, metus. Nullam accumsan lorem in dui. Cras ultricies mi eu turpis hendrerit fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ac dui quis mi consectetuer lacinia. Nam pretium turpis et arcu. Duis arcu tortor, suscipit eget, imperdiet nec, imperdiet iaculis, ipsum. Sed aliquam ultrices mauris. Integer ante arcu, accumsan a, consectetuer eget, posuere ut, mauris. Praesent adipiscing. Phasellus ullamcorper ipsum rutrum nunc. Nunc nonummy metus. Vestibulum volutpat pretium libero. Cras id dui. Aenean ut</p>


							<!-- Condizioni di utilizzo FINE -->

						</div>
					</div>

					<br>

					<div class="row">
						<div class="col-md-12 center">
							<%= f.check_box :condizioni, class: 'square-red' %>
							Dichiaro di aver letto, compreso e accettato le condizioni di utilizzo
						</div>
					</div>

					<div class="row">
						<div class="col-md-12">
							<%= f.submit 'Registrati', :class => 'btn btn-success' %>
						</div>
					</div>

				</div>
			</div>

			<br>

		<% end %>

	</div>
</section>


</div>




app/views/welcome/_header_prelogin.html.erb
<!-- start: HEADER -->
		<header>
			

			<div role="navigation" class="navbar navbar-default navbar-fixed-top">
				<!-- start: TOP NAVIGATION CONTAINER -->
				<div class="container">
					<div class="navbar-header">
						<!-- start: RESPONSIVE MENU TOGGLER -->
						<button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- end: RESPONSIVE MENU TOGGLER -->
						<!-- start: LOGO -->
						<!-- <a class="navbar-brand" href="index.html">
							Assistenza<i class="fa fa-lightbulb-o"></i>Tecnica
						</a> -->
						<%= link_to 'Assistenza<i class="fa fa-lightbulb-o"></i>Tecnica'.html_safe, root_path, class: 'navbar-brand' %>
						<!-- end: LOGO -->
					</div>
					<div class="navbar-collapse collapse">
						<ul class="nav navbar-nav navbar-right">
							<li class="<%= 'active' if current_page?(welcome_prelogin_path) %>">
								<%= link_to "home", welcome_prelogin_path %>
							</li>
							
							<li class="<%= 'active' if (params[:controller] == 'welcome' && params[:action] == 'justone') %>">
								<%= link_to 'Just<i class="clip-seven-segment-1"></i> One'.html_safe, '#responsive', "data-toggle" => "modal" %>
							</li>

							<li>
								<%= link_to 'Registrazione'.html_safe, welcome_prelogin_path(:registrazione => 'new') %>
							</li>

							<li>
								<%= link_to 'Login', welcome_login_path %>
							</li>

						</ul>
					</div>
				</div>
				<!-- end: TOP NAVIGATION CONTAINER -->
			</div>
		</header>
		<!-- end: HEADER -->

app/views/welcome/aperti.html.erb

<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Interventi aperti
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="dataTable_wrapper">
					<table class="table table-striped table-bordered table-hover" id="dataTables-aperti">
						<thead>
						  <tr>
								<th>Cliente</th>
								<th>Descrizione</th>
								<th>Data Apertura</th>
								<th>Tecnico</th>
								<th>Visualizza</th>
						  </tr>
				  	</thead>

				  	<tbody>
						  <% @interventi.each do |intervento| %>
						  <% @cliente = Clienti.find(intervento.cliente_id) %>
						  <% @tecnico = Utenti.find(intervento.operator_id) if intervento.operator_id? %>
							<tr>
							  <td><%= @cliente.nome %></td>
							  <td><%= truncate(intervento.intervento, length: 55, omission: '...(continua)...') %></td>
							  <td><%= intervento.data %></td>
							  <td><%= @tecnico.nome if intervento.operator_id? %></td>
							  <td><%= link_to '<i class="material-icons">pageview</i>'.html_safe, clienti_interventi_path(:clienti_id => intervento.cliente_id, :id => intervento.id) %></td>
							</tr>
						  <% end %>
				  	</tbody>
					</table>
				</div><!-- /.dataTable_wrapper -->
			</div><!-- /.panel-body -->
		</div><!-- /.panel panel-default -->
	</div><!-- /.col -->
</div><!-- /.row -->



<script>/*
	$(document).ready(function() {
		$('#dataTables-aperti').DataTable({
              responsive: true,
              "order": [[ 0, "asc" ]],
				 "language": {
								"lengthMenu": "Visualizza _MENU_ records per pagina",
								"zeroRecords": "Nessun risultato - spiacente",
								"info": "Sei a pagina _PAGE_ di _PAGES_",
								"infoEmpty": "Nessun record disponibile",
								"infoFiltered": "(filtrati fra _MAX_ record totali)",
								"paginate": {
											  "next": "Successiva",
											  "previous": "Precedente"
											}
							}
      });
	});*/
</script>

app/views/welcome/assegnati.html.erb
<div class="row">
	<div class="col-lg-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				Interventi assegnati a me
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
				<div class="dataTable_wrapper">
					<table class="table table-striped table-bordered table-hover" id="dataTables-aperti">
						<thead>
						  <tr>
								<th>Cliente</th>
								<th>Data Apertura</th>
								<th>Descrizione</th>
								<th>Visualizza</th>
						  </tr>
				  	</thead>

				  	<tbody>
						  <% @assegnati.each do |intervento| %>
						  <%	@cliente = Clienti.find(intervento.cliente_id) %>
							<tr>
							  <td><%= @cliente.nome %></td>
							  <td><%= intervento.data %></td>
							  <td><%= intervento.intervento %></td>
							  <td><%= link_to '<i class="material-icons">pageview</i>'.html_safe, clienti_interventi_path(:clienti_id => intervento.cliente_id, :id => intervento.id) %></td>
							</tr>
						  <% end %>
				  	</tbody>
					</table>
				</div><!-- /.dataTable_wrapper -->
			</div><!-- /.panel-body -->
		</div><!-- /.panel panel-default -->
	</div><!-- /.col -->
</div><!-- /.row -->

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/idex.html.erb</p>


<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
 </div>
<% end %>

<% if !flash[:error].blank? %>
   <div class = "alert alert-info">
      <%= alert %>
 </div>
<% end %>
<br>


<p>Ci sono <%= @conta_aperti %> interventi aperti. Clicca <%= link_to 'quì', welcome_aperti_path %> per visualizzarli</p>
<hr>
<p>Hai un credito residuo per gli sms di €<%= @credito_skebby.round(2) %></p>
<hr>
<p><%= link_to "Pagina guest", welcome_prelogin_path %></p>
<hr>

<% if utenti_signed_in? %>
	<p>Sei loggato come:<%= current_utenti.email  %> </p>
<% end %>

<% flash.each do |key, value| %>
		<hr>
        <div class="alert alert-<%= key %>">
        	<%= key %> : <%= value %>
        </div>
		<hr>
	<% end %>

<hr>


<p>Sono Guest = <% if !utenti_signed_in? %> <%= 'si' %> <% else  %> <%= 'no' %> 	<% end	%> | <%= @sono_guest %> </p>

<p>Sono loggato =  <% if utenti_signed_in? %> <%= 'si' %> <% else  %> <%= 'no' %> 	<% end	%> | <%= @sono_loggato %></p>

<p>Amministratore = <% if utenti_signed_in? && current_utenti.admin? %> <%= 'si' %> <% else  %> <%= 'no' %> 	<% end	%> | <%= @sono_admin %></p>

<p>Sono Operatore = <% if utenti_signed_in? && (current_utenti.admin? || current_utenti.operatore? ) %> <%= 'si' %> <% else  %> <%= 'no' %> 	<% end	%> | <%= @sono_operatore %> </p>


<p>Sono urer = <%= @sono_user %></p>



<!-- 	-->
<hr>
<h4>Da fare</h4>
<p>sistemare icone, ove possibile proseguire sulla dicitura eliminando le icone</p>
<p>se possibile variare le notifiche con popup</p>
<p>------------------------------------</p>

<p>Permessi per operatore<br>
da operatore: elenco interventi assegnati con evidenza per nuovi e aperti<br></p>

<p>Assegnazione login a cliente (problemi nel controller su azione new renderizzata da create<br>
Se durante l'assegnazione, non passano le validazioni, correggendo e reinviando non viene legato l'utente al cliente.<br>
Il problema sta nella variabile url che scompare e di conseguenza la variabile @miocliente non viene dichiarata e la<br>
form-field-hidden con id 'utentis_clienti_id' non viene renderizzata e compilata.</p>

<!-- 	-->
<hr>




<%= debug(params) %>

<script>
	function cookie_barra_aperta() {
		document.cookie = 'navigation=aperta'; 
	}

	function cookie_barra_chiusa() {
		document.cookie = 'navigation=chiusa'; 
	}

</script>

app/views/welcome/prelogin.html.erb
<head>
<title>Gestione Assistenza</title>
  <!-- start: META -->
	<meta charset="utf-8" />
	<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta content="" name="description" />
	<meta content="" name="author" />
	<!-- end: META -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
                    <%= stylesheet_link_tag "/assets/plugins/bootstrap/css/bootstrap.min", media: "all" %>
                    <%= stylesheet_link_tag "/assets/plugins/font-awesome/css/font-awesome.min", media: "all" %>
                    <%= stylesheet_link_tag "/assets/fonts/style", media: "all" %>
                    <%= stylesheet_link_tag "/assets_fe/plugins/animate.css/animate.min", media: "all" %>
                    <%= stylesheet_link_tag "/assets_fe/css/main", media: "all" %>
                    <%= stylesheet_link_tag "/assets_fe/css/main-responsive", media: "all" %>
                    <%= stylesheet_link_tag "/assets_fe/css/theme_blue", media: "all" %>
                    <!-- end main js -->

                    <!-- js specifici -->
                    <%= stylesheet_link_tag "/assets/plugins/revolution_slider/rs-plugin/css/settings" %>
                    <%#= stylesheet_link_tag "/assets/plugins/flex-slider/flexslider" %>
                    <%= stylesheet_link_tag "/assets/plugins/colorbox/example2/colorbox" %>

                    <%= stylesheet_link_tag "/assets/plugins/bootstrap-modal/css/bootstrap-modal-bs3patch.css", media: "all" %>
                    <%= stylesheet_link_tag "/assets/plugins/bootstrap-modal/css/bootstrap-modal.css", media: "all" %>
                    <!-- fine specifici -->

  <%#= stylesheet_link_tag "/assets/plugins/iCheck/skins/all", media: "all" %>
  <%#= stylesheet_link_tag "/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette", media: "all" %>
  <%#= stylesheet_link_tag "/assets/plugins/perfect-scrollbar/src/perfect-scrollbar", media: "all" %>
                  <%#= stylesheet_link_tag "/assets/css/theme_light", media: "all" %>
  <%#= stylesheet_link_tag "/assets/plugins/datepicker/css/datepicker", media: "all" %>
  <%#= stylesheet_link_tag "/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3", media: "all" %>

  <!-- start: HTML5SHIV FOR IE8 -->
    <!--[if lt IE 9]>
    <script src="assets/plugins/html5shiv.js"></script>
    <![endif]-->
    <!-- end: HTML5SHIV FOR IE8 -->
 
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
<%# if current_page?(welcome_prelogin_path) %> 
<%= render 'header_prelogin' %>

<%= render 'body_prelogin' if !params[:registrazione] %>
<%= render 'body_registrazione' if params[:registrazione] %>

<%#= debug(params) %>

<%= render 'footer_prelogin' %>


<!--    Inizio Modal -->
<div id="responsive" class="modal fade" tabindex="-1" data-width="760" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
      &times;
    </button>
    <h4 class="modal-title">Just<i class="clip-seven-segment-1"></i> One - Controlla il tuo intervento</h4>
  </div>
  <div class="modal-body">
    <div class="row">
      <div class="col-md-12">
        <%= form_for :justone, url: welcome_justone_path  do |f| %>

          <%= f.label "Codice Cliente" %>
          <%= f.number_field :cod_cli, class: 'form-control' %>

          <%= f.label "Codice Intervento" %>
          <%= f.text_field :cod_int, class: 'form-control' %>

      </div>
    </div>  
  </div>
  <div class="modal-footer">
          <%= f.submit 'Cerca', :class => 'btn btn-success' %>
        <% end %>
  </div>
</div>
<!--  Fine Modal -->






<!-- start: MAIN JAVASCRIPTS -->
<!--[if lt IE 9]>
<%= javascript_include_tag "/assets_fe/plugins/respond.min" %>
<%= javascript_include_tag "/assets_fe/plugins/excanvas.min" %>
<%= javascript_include_tag "/assets_fe/plugins/html5shiv" %>
<%= javascript_include_tag "/assets_fe/plugins/jQuery-lib/1.10.2/jquery.min" %>
<![endif]-->
<!--[if gte IE 9]><!-->
<%= javascript_include_tag "/assets/plugins/jQuery-lib/2.0.3/jquery.min" %>
<!--<![endif]-->
<%= javascript_include_tag "/assets/plugins/bootstrap/js/bootstrap.min" %>
<%= javascript_include_tag "/assets/plugins/jquery.transit/jquery.transit" %>
<%= javascript_include_tag "/assets/plugins/hover-dropdown/twitter-bootstrap-hover-dropdown.min" %>
<%= javascript_include_tag "/assets/plugins/jquery.appear/jquery.appear" %>
<%= javascript_include_tag "/assets/plugins/blockUI/jquery.blockUI" %>
<%= javascript_include_tag "/assets/plugins/jquery-cookie/jquery.cookie" %>
<%= javascript_include_tag "/assets_fe/js/main" %>
<!-- end: MAIN JAVASCRIPTS -->
<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<%#= javascript_include_tag "/assets_fe/plugins/revolution_slider/rs-plugin/js/jquery.themepunch.plugins.min" %>
<%#= javascript_include_tag "/assets_fe/plugins/revolution_slider/rs-plugin/js/jquery.themepunch.revolution.min" %>
<%#= javascript_include_tag "/assets_fe/plugins/flex-slider/jquery.flexslider" %>
  <%#= javascript_include_tag "/assets_fe/plugins/stellar.js/jquery.stellar.min" %>
<%= javascript_include_tag "/assets/plugins/colorbox/jquery.colorbox-min" %>
<%= javascript_include_tag "/assets_fe/js/index" %>


<%= javascript_include_tag "/assets/plugins/bootstrap-modal/js/bootstrap-modal.js" %>
<%= javascript_include_tag "/assets/plugins/bootstrap-modal/js/bootstrap-modalmanager" %>
<%= javascript_include_tag "/assets/js/ui-modals" %>
<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
<script>
	jQuery(document).ready(function() {
		Main.init();
    UIModals.init();
		//Index.init();
		//$.stellar();
	});
</script>

</body>