config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :utentis, :path_prefix => 'my'#, :skip => [:registrations]
  resources :utentis

  root to: "welcome#index"
  get 'welcome/aperti', :path => "aperti"
  get 'welcome/prelogin'
  get 'welcome/justone'
  post 'welcome/justone'
  get 'welcome/login', :path => 'login'
  get 'welcome/login'
  get 'welcome/assegnati', :path => 'assegnati'
  get 'welcome/elenco', :path => 'elenco'
  get 'welcome/richiedi', :path => 'richiedi'
  post 'welcome/richiesta'
  post 'welcome/registrazione', :path => 'registrazione'

  

  resources :clienti do
    resources :contrattis
    resources :interventi do
      
      get :sms
      get :allega
      get :vediallegato
      patch :salva_allegato
      get :elimina_allegato
        resources :intallegatis
        resources :comunicazioni
        resources :works do
          get :allega
          patch :salva_allegato
          get :elimina_allegato
          get :vedi_allegato
        end
    end
  end

 
  

  

end

app/models/clienti.rb
class Clienti < ActiveRecord::Base
	has_many :interventi, :dependent => :destroy, :foreign_key => "cliente_id"
	#has_many :comunicazioni, :through => :interventi, :dependent => :destroy
	has_many :contratti, :dependent => :destroy
	has_many :works, :through => :interventi, :dependent => :destroy
	
	#gestione autenticazione
	has_one :utenti, :foreign_key => 'clienti_id', :dependent => :destroy
	
	validates :nome, presence: true, length: {minimum: 5 }
	validates :telefono, presence: true, length: {minimum: 9}, numericality: true
end

app/controllers/clienti_controller.rb
class ClientiController < ApplicationController

	#before_action :authenticate_utenti!
	before_filter :authenticate_utenti!
	before_filter :is_admin?#, :except => :show
	
	def index
		@clienti = Clienti.all
		@titolo = "Anagrafica Clienti"
	end

	def show
		@titolo = "Dettagli Anagrafica"
		@clienti = Clienti.find(params[:id])
		#@intervtot = Interventi.where(cliente_id: @clienti).count
		@intervtot = @clienti.interventi.count
		#@intervaperti = Interventi.where(cliente_id: @clienti, chiuso: '0').count
		@intervaperti = @clienti.interventi.where(chiuso: '0').count

		# generare variabili per interventi aperti e ore da contratto residue
		#@aperti = Clienti.Interventi

		rescue ActiveRecord::RecordNotFound  
		 flash[:errore] = "Errore nella query - clienti"
		 redirect_to :controller => "welcome", :action => "index"
		return
	end

	def new
		@titolo = "Nuovo Cliente"
		@clienti = Clienti.new
	end

	def edit
		@clienti = Clienti.find(params[:id])

		rescue ActiveRecord::RecordNotFound  
		 flash[:errore] = "Errore nella query - clienti"
		 redirect_to :controller => "welcome", :action => "index"
		return
	end

	def create
		@titolo = "Nuovo Cliente"
		@clienti = Clienti.new(clienti_params)
		if @clienti.save
			redirect_to @clienti, notice: "Cliente aggiunto"
		else
			logger.info "mancano dati - ritorno a new"
			render 'new'
		end
	end

	def update
	  @clienti = Clienti.find(params[:id])
	 
	  if @clienti.update(clienti_params)
	    redirect_to @clienti
	  else
	    render 'edit'
	  end
	end

	def destroy
		@clienti = Clienti.find(params[:id])
	  @clienti.destroy
	  #redirect_to clienti_path
	  redirect_to clienti_index_path, notice: "Cliente eliminato"
	end

	private
		def clienti_params
			params.require(:clienti).permit(:nome, :piva, :codfisc, :email, :telefono, :note)
		end

		

end

app/helpers/clienti_helper.rb
module ClientiHelper
end

app/views/clienti/_form.html.erb
<% if local_assigns.has_key? :url %>
  <%= form_for :clienti, url: url, method: method, class: "col s12" do |f| %>   


  <div class="row">
    <div class="col-md-12">
      <%= f.label :nome %>
      <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-user"></i></span>
        <%= f.text_field :nome, :length=>"254", class: "form-control" %>
      </div>
    </div>
  </div>

  <!-- -->

  <div class="row">
    <div class="col-md-6">
      <%= f.label :codfisc %>
      <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-barcode"></i></span>
        <%= f.text_field :codfisc, :length=>"16", :maxlength=>"16", class: "form-control" %>
      </div>
    </div>

    <div class="col-md-6">
      <%= f.label :piva %>
      <div class="form-group input-group">
        <span class="input-group-addon"><i class="fa fa-barcode"></i></span>
        <%= f.text_field :piva, :length=>"16", :maxlength=>"18", class: "form-control" %>
      </div>
    </div>
  </div>
  
  <!-- -->

  <div class="row">
    <div class="col-md-6">
      <%= f.label :telefono %>
       <div class="form-group input-group">
          <span class="input-group-addon"><i class="fa fa-phone-square"></i></span>
          <%= f.text_field :telefono, :length=>"15", class: "form-control" %>
       </div>
    </div>

    <div class="col-md-6">
        <%= f.label :email %>
       <div class="form-group input-group">
          <span class="input-group-addon"><i class="fa fa-envelope-o"></i></span>
          <%= f.text_field :email, class: "form-control" %>
       </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
       <div class="form-group">
          <%= f.label :note %><%= f.text_area :note, class: "form-control" %>
       </div>
    </div>
  </div>


  <div class="row">
    <div class="col-md-3">
       <div class="form-group">
        <%= link_to 'Indietro', clienti_index_path, class: 'btn btn-danger' %>
        <%= f.submit 'Salva', :class => 'btn btn-success' %>
       </div>
    </div>
  </div>

<!--      -->
  <% end %>
<% end %>

app/views/clienti/_gestione_errori.html.erb
<% if @clienti.errors.any? %>

<div class="divider"></div>
  <div class="row">
    <div class="col-md-12">
      <div class="alert alert-danger">
        <h4><%= pluralize(@clienti.errors.count, "error") %> impediscono il salvataggio del cliente: </h4>
        <ul class="list-unstyled">
          <% @clienti.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="divider"></div>

<% end %>

app/views/clienti/edit.html - Copia.erb
<h1>Modifica Cliente</h1>
 <div class='row'>
  <%#= render 'form' %>
 
 
 <%= form_for :clienti, url: clienti_path(@clienti), method: :patch, class: "col s12" do |f| %>   
 	<% if @clienti.errors.any? %>
    <div class="row">
      <div class="col s12">
        <div id="error_explanation">
          <h4><%= pluralize(@clienti.errors.count, "error") %> impediscono il salvataggio del cliente: </h4>
          <ul class="collection">
            <% @clienti.errors.full_messages.each do |msg| %>
              <li class="collection-item"><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <% end %>


    <div class="row">
      <div class="input-field col s12 hoverable">
        <i class="material-icons prefix">account_circle</i>
        <%= f.label :nome %><br><%= f.text_field :nome %>
      </div>
    </div>
  

  <div class="row">
    <div class="input-field col s6 hoverable">
      <i class="material-icons prefix">subtitles</i>
      <%= f.label :codfisc %><br><%= f.text_field :codfisc %>
    </div>

    <div class="input-field col s6 hoverable">
      <i class="material-icons prefix">work</i>
      <%= f.label :piva %><br><%= f.text_field :piva %>
    </div>  
  </div>
  

  <div class="row">
    <div class="input-field col s6 hoverable">
      <i class="material-icons prefix">phone</i>
      <%= f.label :telefono %><br><%= f.text_field :telefono %>
    </div>

    <div class="input-field col s6 hoverable">
      <i class="material-icons prefix">email</i>
      <%= f.label :email %><br><%= f.text_field :email %>
    </div>
  </div>


  
  <div class="row">
    <div class="input-field col s12 hoverable">
      <i class="material-icons prefix">speaker_notes</i>
      <%= f.label :note %><br><%= f.text_area :note, class: 'materialize-textarea' %>
    </div>
  </div>
<!--
<div class="row">
  <div class="col s3">
    <%= f.submit 'Aggiorna', :class => 'btn waves-effect waves-light'  %>
  </div>
  <div class col s3>
    <%= link_to '<i class="material-icons left">fast_rewind</i>Indietro'.html_safe, clienti_index_path, class: 'waves-effect waves-light btn' %>
  </div>
</div>
-->
<div class="row">
<ul class="lista-pulsanti">
  <li><%= link_to '<i class="material-icons left">fast_rewind</i>Indietro'.html_safe, clienti_index_path, class: 'waves-effect waves-light btn' %></li>
  <li><%= f.submit 'Aggiorna', :class => 'btn waves-effect waves-light'  %></li>
</ul>
</div>

	
<% end %>




app/views/clienti/edit.html.erb
<div class="row">
  <div class="col s12 center-align">
    <h3>Modifica Cliente</h3>
  </div>
</div>
<div class="divider"></div>


<%= render'gestione_errori' %>

<%= render 'form', {url: clienti_path(@clienti), method: 'patch'} %>

<div class="divider"></div>



<%= debug(params) %>

app/views/clienti/index.html.erb
<% if !flash[:notice].blank? %>
   <div class = "alert alert-info">
      <%= flash[:notice] %>
 </div>
<% end %>



<div class="row">
	<div class="col-md-3">
		<%= link_to 'Nuovo Cliente', new_clienti_path, class: "btn btn-primary" %>
	</div>	
</div>


<br>


<div class="divider"></div>

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<i class="clip-users-2"></i>
				Clienti Censiti
			</div>
			<!-- /.panel-heading -->
			<div class="panel-body">
					<table class="table  table-hover" id="dataTables-clienti">
						<thead>
						  <tr>
								<th><i class="material-icons">perm_identity</i>Nome</th>
								<th><i class="material-icons">drafts</i>Email</th>
								<th class="hidden-xs"><i class="material-icons">phone</i>Telefono</th>
								<th>Login</th>
								<!-- <th>Visualizza</th> -->
						  </tr>
					  </thead>
					 
					 	<tbody>
						  <% @clienti.each do |cliente| %>
								<tr>
									<td><%= link_to cliente.nome, clienti_path(cliente) %> <%= ('<span class="label label-danger"> Pending Approvation</span>'.html_safe if !cliente.utenti.approved) if cliente.utenti %> 
									</td>
									<td><%= cliente.email %></td>
									<td class="hidden-xs"><%= cliente.telefono %></td>
									<td><%#= cliente.utenti ? "<span class='label label-success'><i class='fa clip-user-3'></i> #{cliente.utenti.email}</span>".html_safe : (link_to '<i class="fa fa-chain-broken"></i> Associa Login'.html_safe, new_utenti_path( :varcliente => cliente.id), class: 'btn btn-xs btn-bricky') %>

										<%= cliente.utenti ? cliente.utenti.email : (link_to '<i class="fa fa-chain-broken"></i> Associa Login'.html_safe, new_utenti_path( :varcliente => cliente.id), class: 'btn btn-xs btn-bricky') %>

									</td>
									<!--
									<td align="center"><%= link_to '<i class="fa fa-folder-open-o"></i>'.html_safe, clienti_path(cliente), class: 'btn btn-xs btn-teal tooltips', "data-placement" => 'top', "data-original-title" => 'Dettagli Cliente' %></td>
									-->
								</tr>
						  <% end %>
					  </tbody>
					</table>
				<!-- </div> --><!-- /.dataTable_wrapper -->
			</div><!-- /.panel-body -->
		</div><!-- /.panel panel-default -->
	</div><!-- /.col -->
</div><!-- /.row -->

<%= debug(params) %>



<script>
	$(document).ready(function() {
		$( '#dataTables-clienti' ).dataTable({
				responsive: true,
				//sort: "Proprietario"
				//"order": [[ 0, "desc" ]],
				 "oLanguage": {
								"sLengthMenu": "Visualizza _MENU_ records per pagina",
								"sZeroRecords": "Nessun risultato - spiacente",
								"sInfo": "Stai visualizzando i record da _START_ a _END_ (_TOTAL_ in totale)",
								"sInfoEmpty": "Nessun record disponibile",
								"sInfoFiltered": "(filtrati fra _MAX_ record totali)",
								"oPaginate": {
											  "sNext": "Successiva",
											  "sPrevious": "Precedente"
											}
							}
		});
	});
</script>

app/views/clienti/new.html.erb


<%= render'gestione_errori' %>


<%#= render 'form' %>
<%= render 'form', {url: clienti_index_path, method: 'nessuno'} %>


<div class="divider"></div>

<%= debug(params) %>

app/views/clienti/show.html.erb
<div class="row">
	<div class="col-lg-6">
		<div class="well well-lg">
			<div class="row">
				<div class="col-md-12">
					<!-- -->
					<div class="dropdown pull-right">
					  <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
					    Azioni
					    <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
					    <li><%= link_to 'Modifica', edit_clienti_path(@clienti) %></li>
					    <li><%= link_to 'Elimina', clienti_path(@clienti.id), method: :delete, data: { confirm: 'Sicuro di voler eliminare il cliente? Non è reversibile' } %></li>
					    <!--<li><%= link_to 'Invia Comunicazione', root_path %></li> -->
					    <li class="divider"></li>
					    <li>
					    	<% if @clienti.utenti %>
					    		<%= link_to 'Abilita Accesso', '#' if !@clienti.utenti.approved %>
					    		<%= link_to 'Blocca Accesso', '#' if @clienti.utenti.approved %>
					    	<% end %>
					    </li>
					  </ul>
					</div>
				 	<!-- 	-->
				 	<h4 class="center">Cliente: <%= @clienti.nome %></h4>

				 	<dl class="dl-horizontal">
						<dt><strong>P.iva: </strong></dt><dd><%= @clienti.piva%></dd>
						<dt><strong>C.F.: </strong></dt><dd><%= @clienti.codfisc%></dd>
						<dt><strong>E-Mail: </strong></dt><dd><%= @clienti.email%></dd>
						<dt><strong>Telefono: </strong></dt><dd><%= @clienti.telefono%></dd>
						<dt><strong>Login: </strong></dt><dd><%= @clienti.utenti ? @clienti.utenti.email : "---ATTENZIONE--- Nessuna login associata !!".html_safe %>
						</dd>
					</dl>
					
					<% if @clienti.utenti && !@clienti.utenti.approved %>
						<div align="center"><span class="label label-danger"> Utenza registrata dal Front-End in attesa di approvazione o comunque disabilitata</span></div>
					<% end %>

				</div>
			</div>
		</div>
	</div>
	<div class="col-lg-6">
		<div class="well well-lg">
			<div class="row">
				<div class="col-md-6">

					<button onclick="location.href='<%= clienti_interventi_index_path(:clienti_id => @clienti.id) %>';" class="btn btn-icon btn-block" id="pulsanteInterventi" name="pulsanteInterventi" type="submit">
						<i class="fa fa-comments-o"></i><%= @intervtot %> Interventi <span class="badge badge-danger"> <%= @intervaperti %> </span>
					</button>

				</div>
				<div class="col-md-6">

					<button onclick="location.href='<%= clienti_contrattis_path(:clienti_id => @clienti.id) %>';" class="btn btn-icon btn-block" id="pulsanteContratti" name="pulsanteContratti" type="submit">
						<i class="fa fa-comments-o"></i>Contratti <span class="badge badge-success"> 33 </span>
					</button>

				</div>
			</div>
			<div class="row"></div>

		</div>
	</div>
</div>

<div class="divider"></div>
<!--
<%# per linkare alla pagina successiva, modificando un parametro di post, traducendo quindi il pramaetro "clienti.id" fornito in quest pagina in "clienti_id" come richiesto dalla pagina successiva %>
<%#= link_to 'Aggiungi Intervento', new_clienti_interventi_path(:clienti_id => @clienti.id) %>
-->
<div class="row">
	<div class="col-lg-12">
		<%= link_to 'Indietro', clienti_index_path, class: 'btn btn-danger' %>
		<%#= link_to 'Gestione Contratti', clienti_contrattis_path(:clienti_id => @clienti.id), class: 'btn btn-purple' %>
		<%#= link_to 'Elenco Interventi', clienti_interventi_index_path(:clienti_id => @clienti.id), class: 'btn btn-primary' %>
		<%= link_to 'Nuovo Intervento', new_clienti_interventi_path(:clienti_id => @clienti.id), class: 'btn btn-success' %>
		<%= link_to '<i class="fa clip-user-3"></i> Associa Login'.html_safe, new_utenti_path( :varcliente => @clienti.id), class: 'btn btn-bricky' if !@clienti.utenti %>
	</div>
</div>
<div class="divider"></div>

<%= debug(params) %>

<script>
			jQuery(document).ready(function() {
				Main.init();
				//TableData.init();
				//UIElements.init();
				//FormElements.init();
				UIButtons.init();
			});
	</script>