config/routes.rb
Rails.application.routes.draw do
  
  

  devise_for :utentis, :path_prefix => 'my'#, :skip => [:registrations]
  resources :utentis

  root to: "welcome#index"
  get 'welcome/aperti', :path => "aperti"
  get 'welcome/prelogin'
  get 'welcome/justone'
  post 'welcome/justone'
  get 'welcome/login', :path => 'login'
  get 'welcome/login'
  get 'welcome/assegnati', :path => 'assegnati'
  get 'welcome/elenco', :path => 'elenco'
  get 'welcome/richiedi', :path => 'richiedi'
  post 'welcome/richiesta'
  post 'welcome/registrazione', :path => 'registrazione'

  

  resources :clienti do
    resources :contrattis
    resources :interventi do
      
      get :sms
      get :allega
      get :vediallegato
      patch :salva_allegato
      get :elimina_allegato
        resources :intallegatis
        resources :comunicazioni
        resources :works do
          get :allega
          patch :salva_allegato
          get :elimina_allegato
          get :vedi_allegato
        end
    end
  end

 
  

  

end

app/views/layouts/_footer.html.erb
<div class="footer clearfix">
	<div class="footer-inner">
		2016 &copy; Francesco Bucci
	</div>
	<div class="footer-items">
		<span class="go-top"><i class="clip-chevron-up"></i></span>
	</div>
</div>

app/views/layouts/_header.html.erb
<!-- start: HEADER -->
		<div class="navbar navbar-inverse navbar-fixed-top">
			<!-- start: TOP NAVIGATION CONTAINER -->
			<div class="container">
				<div class="navbar-header">
					<!-- start: RESPONSIVE MENU TOGGLER -->
					<button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle" type="button">
						<span class="clip-list-2"></span>
					</button>
					<!-- end: RESPONSIVE MENU TOGGLER -->
					<!-- start: LOGO -->
					<%= link_to 'Gestione-Laboratorio', root_path, class: "navbar-brand" %>
					<!-- end: LOGO -->
				</div>
				<div class="navbar-tools">
					<!-- start: TOP NAVIGATION MENU -->
					<ul class="nav navbar-right">
						
						<% if utenti_signed_in? %>

						<!-- start: USER DROPDOWN -->
						<li class="dropdown current-user">

							<a data-toggle="dropdown" data-hover="dropdown" class="dropdown-toggle" data-close-others="true" href="#">
								<%= image_tag("user_blank.gif", size: '25x25', class: "circle-img") %>
								<span class="username"><%= current_utenti.nome  %></span>
								<i class="clip-chevron-down"></i>
							</a>
							<ul class="dropdown-menu">
								<li>
									<i class="clip-steam"></i><%= current_utenti.admin ? ' Amministratore' : current_utenti.operatore ? ' Operatore' : ' User' %>
								</li>

								<li>
									<%= link_to '<i class="clip-user-2"></i> Profilo'.html_safe, edit_utenti_registration_path %>
								</li>

								<li>
									<a href="pages_calendar.html">
										<i class="clip-calendar"></i>
										&nbsp;My Calendar
									</a>
								</li>
								<li>
									<a href="pages_messages.html">
										<i class="clip-bubble-4"></i>
										&nbsp;My Messages (3)
									</a>
								</li>
								<li class="divider"></li>
								<li>
									<a href="utility_lock_screen.html"><i class="clip-locked"></i>
										&nbsp;Lock Screen </a>
								</li>
								<li>
									<%= link_to '<i class="clip-exit"></i> Log Out'.html_safe, destroy_utenti_session_path, :method => :delete %>
								</li>
							</ul>
						</li>
						<!-- end: USER DROPDOWN -->

						<% else %>

						<li>
							<%= link_to 'Accedi', new_utenti_session_path %>
						</li>

						<% end %>

					</ul>
					<!-- end: TOP NAVIGATION MENU -->
				</div>
			</div>
			<!-- end: TOP NAVIGATION CONTAINER -->
		</div>
		<!-- end: HEADER -->

app/views/layouts/_navbar.html.erb
<div class="navbar-content">
	<!-- start: SIDEBAR -->
	<div class="main-navigation navbar-collapse collapse">
		<!-- start: MAIN MENU TOGGLER BUTTON -->
		<div class="navigation-toggler">
			<i class="clip-chevron-left"></i>
			<i class="clip-chevron-right"></i>
		</div>
		<!-- end: MAIN MENU TOGGLER BUTTON -->
		<!-- start: MAIN NAVIGATION MENU -->
		<ul class="main-navigation-menu">
			<li class="<% if current_page?(:controller => '/welcome', :action => 'index') %> <%= "active open" %> <% end %>" >
				<%= link_to '<i class="clip-home-3"></i><span class="title"> Dashboard</span>'.html_safe, root_path %>
			</li>

			<% if utenti_signed_in? && current_utenti.admin %>
				<li class="<% if current_page?(:controller => '/clienti', :action => 'index') %> <%= "active open" %> <% end %>">
					<%= link_to '<i class="clip-users-2"></i><span class="title"> Gestione Clienti</span>'.html_safe, clienti_index_path %>
				</li>

				<li class="<% if current_page?(:controller => '/utentis', :action => 'index') %> <%= "active open" %> <% end %>">
					<%= link_to '<i class="material-icons">perm_identity</i><span class="title"> Gestione Accessi</span>'.html_safe, utentis_path %>
				</li>

				<li class="<% if current_page?(:controller => '/welcome', :action => 'aperti') %> <%= "active open" %> <% end %>">
					<%= link_to '<i class="clip-folder"></i><span class="title"> Interventi Aperti</span>'.html_safe, welcome_aperti_path %>
				</li>

			<% end %>

			<% if utenti_signed_in? && (current_utenti.operatore? || current_utenti.admin) %>
				<li class="<% if current_page?(:controller => '/welcome', :action => 'assegnati') %> <%= "active open" %> <% end %>">
					<%= link_to '<i class="clip-folder"></i><span class="title"> I Miei Interventi</span>'.html_safe, welcome_assegnati_path %>
				</li>
			<% end %>


			<% if utenti_signed_in? && current_utenti.admin %>
				<li class="<%# if current_page?(:controller => '/admin', :action => 'index') %> <%#= "active open" %> <%# end %>">
					<%= link_to '<i class="clip-folder"></i><span class="title"> Setup'.html_safe, welcome_assegnati_path %>
				</li>
			<% end %>



			<% if @sono_user %>
				<li>
					<%= link_to '<i class="clip-folder"></i><span class="title"> I miei Ticket</span>'.html_safe, welcome_elenco_path %>
				</li>
				<li>
					<%= link_to '<i class="clip-folder"></i><span class="title"> Richiedi Intervento</span>'.html_safe, welcome_richiedi_path %>
				</li>


				<li>
					<a href="#"><span class="title">Codice Cliente: <%= current_utenti.clienti_id %></span></a>
				</li>
			<% end %>

		</ul>
		<!-- end: MAIN NAVIGATION MENU -->
	</div>
	<!-- end: SIDEBAR -->
</div>



app/views/layouts/login_layout.html.erb
<head>
	<!-- Pagina di Login -->
	<title>Area Clienti - Accesso richiesto</title>
	<!-- start: META -->
	<meta charset="utf-8" />
	<!--[if IE]><meta http-equiv='X-UA-Compatible' content="IE=edge,IE=9,IE=8,chrome=1" /><![endif]-->
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0">
	<meta name="apple-mobile-web-app-capable" content="yes">
	<meta name="apple-mobile-web-app-status-bar-style" content="black">
	<meta content="" name="Login Page" />
	<meta content="" name="FrancescoBucci" />
	<!-- end: META -->
	<!-- start: MAIN CSS -->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "/assets/plugins/bootstrap/css/bootstrap.min", media: "all" %>
  <%= stylesheet_link_tag "/assets/plugins/font-awesome/css/font-awesome.min", media: "all" %>
  <%= stylesheet_link_tag "/assets/fonts/style", media: "all" %>
  <%= stylesheet_link_tag "/assets/css/main", media: "all" %>
  <%= stylesheet_link_tag "/assets/css/main-responsive", media: "all" %>
  <%= stylesheet_link_tag "/assets/plugins/iCheck/skins/all", media: "all" %>
  <%= stylesheet_link_tag "/assets/plugins/bootstrap-colorpalette/css/bootstrap-colorpalette", media: "all" %>
  <%= stylesheet_link_tag "/assets/plugins/perfect-scrollbar/src/perfect-scrollbar", media: "all" %>
  <%= stylesheet_link_tag "/assets/css/theme_light", media: "all" %>
  <%= stylesheet_link_tag "/assets/css/print", media: "print" %>

	<!--[if IE 7]>
	<%= stylesheet_link_tag "/assets/plugins/font-awesome/css/font-awesome-ie7.min" %>
	<![endif]-->
	<!-- end: MAIN CSS -->
	<!-- start: CSS REQUIRED FOR THIS PAGE ONLY -->
	<!-- end: CSS REQUIRED FOR THIS PAGE ONLY -->
</head>
<!-- end: HEAD -->
<!-- start: BODY -->
<body class="login example1">
	<div class="main-login col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
		<div class="logo">Customer Area</div>
		<!-- start: LOGIN BOX -->
		<div class="box-login">
			<h3>Accedi al tuo account</h3>

			<% if !flash[:notice].blank? %>
			   <div class = "alert alert-info">
			      <%= flash[:notice] %>
			 </div>
			<% end %>
			<% if !flash[:alert].blank? %>
			   <div class = "alert alert-info">
			      <%= flash[:alert] %>
			 </div>
			<% end %>

			<p>
				Inserisci i tuoi dati.
			</p>
			
			<!-- -->

			<%= form_for :utenti, url: utenti_session_path do |f| %>
				<div class="errorHandler alert alert-danger no-display">
					<i class="fa fa-remove-sign"></i> Ricontrolla, ci sono dei problemi.
				</div>
				<fieldset>
					<div class="form-group">
						<span class="input-icon">
							<%= f.text_field :email, class: 'form-control', placeholder: 'Email' %>
							<i class="fa fa-user"></i> </span>
						<!-- To mark the incorrectly filled input, you must add the class "error" to the input -->
						<!-- example: <input type="text" class="login error" name="login" value="Username" /> -->
					</div>
					<div class="form-group form-actions">
						<span class="input-icon">
							<!-- <input type="password" class="form-control password" name="password" placeholder="Password"> -->
							<%= f.password_field :password, class: 'form-control password', placeholder: 'Password' %>
							<i class="fa fa-lock"></i>
							<a class="forgot" href="?box=forgot">
								Hai perso la password?
							</a> </span>
					</div>
					<div class="form-actions">
						<label for="remember" class="checkbox-inline">
							<!-- <input type="checkbox" class="grey remember" id="remember" name="remember"> -->
							<%= f.check_box :remember_me, class: 'grey remember' %>
							ricordami
						</label>

						<!--<button type="submit" class="btn btn-bricky pull-right">
							Login <i class="fa fa-arrow-circle-right"></i>
						</button> -->
						<%= f.submit 'Login', :class => 'btn btn-bricky pull-right' %>
						<%= link_to 'Indietro', root_path, class: 'btn btn-blue pull-right' %>
					</div>
				</fieldset>
			<!-- </form> -->
			<% end %>
			<!-- 	-->

		</div>
		<!-- end: LOGIN BOX -->
		<!-- start: FORGOT BOX -->
		<div class="box-forgot">
			<h3>Password dimenticata?</h3>
			<p>
				Inserisci la tua e-mail per resettare la password di accesso.
			</p>

			<% if !flash[:notice].blank? %>
			   <div class = "alert alert-info">
			      <%= flash[:notice] %>
			 </div>
			<% end %>
			<% if !flash[:alert].blank? %>
			   <div class = "alert alert-info">
			      <%= flash[:alert] %>
			 </div>
			<% end %>


			<!-- <form class="form-forgot"> -->
			<%= form_for :utenti, url: utenti_password_path, method: :post do |f| %>
				<div class="errorHandler alert alert-danger no-display">
					<i class="fa fa-remove-sign"></i> You have some form errors. Please check below.
				</div>
				<fieldset>
					<div class="form-group">
						<span class="input-icon">
							<!-- <input type="email" class="form-control" name="email" placeholder="Email"> -->
							<%= f.email_field :email, autofocus: true, class: 'form-control', placeholder: 'Email' %>
							<i class="fa fa-envelope"></i> </span>
					</div>
					<div class="form-actions">
						<a href="?box=login" class="btn btn-light-grey go-back">
							<i class="fa fa-circle-arrow-left"></i> Back
						</a>
						<button type="submit" class="btn btn-bricky pull-right">
							Submit <i class="fa fa-arrow-circle-right"></i>
						</button>
					</div>
				</fieldset>
			<!-- </form> -->
			<% end %>
		</div>
		<!-- end: FORGOT BOX -->

		<!-- start: COPYRIGHT -->
		<div class="copyright">
			2016 &copy; FrancescoBucci. - <%= controller_name %> / <%= action_name %>
		</div>
		<!-- end: COPYRIGHT -->
	</div>
	<!-- start: MAIN JAVASCRIPTS -->
	<!--[if lt IE 9]>
	<%= javascript_include_tag "/assets/plugins/respond.min" %>
	<%= javascript_include_tag "/assets/plugins/excanvas.min" %>
	<%= javascript_include_tag "/assets/plugins/jQuery-lib/1.10.2/jquery.min" %>
	<![endif]-->
	<!--[if gte IE 9]><!-->
	<%= javascript_include_tag "/assets/plugins/jQuery-lib/2.0.3/jquery.min" %>
	<!--<![endif]-->
	<%= javascript_include_tag "/assets/plugins/jquery-ui/jquery-ui-1.10.2.custom.min" %>
	<%= javascript_include_tag "/assets/plugins/bootstrap/js/bootstrap.min" %>
	<%= javascript_include_tag "/assets/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min" %>
	<%= javascript_include_tag "/assets/plugins/blockUI/jquery.blockUI" %>
	<%= javascript_include_tag "/assets/plugins/iCheck/jquery.icheck.min" %>
	<%= javascript_include_tag "/assets/plugins/perfect-scrollbar/src/jquery.mousewheel" %>
	<%= javascript_include_tag "/assets/plugins/perfect-scrollbar/src/perfect-scrollbar" %>
	<%= javascript_include_tag "/assets/plugins/less/less-1.5.0.min" %>
	<%= javascript_include_tag "/assets/plugins/jquery-cookie/jquery.cookie" %>
	<%= javascript_include_tag "/assets/plugins/bootstrap-colorpalette/js/bootstrap-colorpalette" %>
	<%= javascript_include_tag "/assets/js/main" %>
	<!-- end: MAIN JAVASCRIPTS -->
	<!-- start: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<%= javascript_include_tag "/assets/plugins/jquery-validation/dist/jquery.validate.min" %>
	<%= javascript_include_tag "/assets/js/login" %>
	<!-- end: JAVASCRIPTS REQUIRED FOR THIS PAGE ONLY -->
	<script>
		jQuery(document).ready(function() {
		//jQuery(document).on('page:change', function() {
			Main.init();
			Login.init();
			//$("input:text:visible:first").focus();
			//FormElements.init();
			$("#utenti_email").focus();
		});
	</script>
</body>
<!-- end: BODY -->

app/views/layouts/old_header.html.erb
<head class="navbar-fixed">
	<nav class="blue-grey darken-2">
		<div class="container nav-wrapper">
			<%= link_to "Gestione Laboratorio", root_path, class: "brand-logo" %>
		  <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		  <ul class="right hide-on-med-and-down">
		    

		    <%# if user_signed_in? %>
		    	<li><%#= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		    <%# else %>
			    <li><%#= link_to "Login", new_user_session_path %></li>
			    <li><%#= link_to "Registrazione", new_user_registration_path %></li>
			<%# end %>

		  </ul>
		  <ul class="side-nav" id="mobile-demo">
		    
		    <% #if user_signed_in? %>
		    	<li><%#= link_to "Logout", destroy_user_session_path, method: :delete %></li>
		    <%# else %>
			    <li><%#= link_to "Login", new_user_session_path %></li>
			    <li><%#= link_to "Registrazione", new_user_registration_path %></li>
			    <li><%= link_to 'Home', root_path %></li>
			    <li><%= link_to "Elenco Clienti", controller: 'clienti' %></li>
			    <li><%= link_to "Interventi Aperti", welcome_aperti_path %></li>
			<%# end %>

		  </ul>
		</div>
	</nav>
</head>